from .node import NODE_CLASS_MAPPINGS as NODE_MAPPINGS_1, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_MAPPINGS_1
from .credentials_node import NODE_CLASS_MAPPINGS as NODE_MAPPINGS_2, NODE_DISPLAY_NAME_MAPPINGS as DISPLAY_MAPPINGS_2

# Combine mappings from both modules
NODE_CLASS_MAPPINGS = {**NODE_MAPPINGS_1, **NODE_MAPPINGS_2}
NODE_DISPLAY_NAME_MAPPINGS = {**DISPLAY_MAPPINGS_1, **DISPLAY_MAPPINGS_2}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]

